### ISSUE TITLE
Oregon trail stuck at now loading the wagon

### ISSUE THREAD

**Issue by patjohnny** [MiSTer-devel/Apple-II_MiSTer#14]
The Oregon trail just freezes after you’re done buying at the store and it goes to Now loading the wagon…
It never gets past that screen. Thanks.
![50C026F3-62FC-46C8-BC8E-AF6581B7B59B](https://user-images.githubusercontent.com/72765243/139502268-6c395894-af32-493e-b9f8-bf10803beb18.jpeg)

**Comment by steven-a-wilson** [comment]
This behavior was seen in mature emulators with the initial release of the 4am crack, which was attributed to "a small data corruption issue". Are you sure that you have a good image?

**Comment by patjohnny** [comment]
I think my set is 4am crack. Is there another set I should look for instead?

**Comment by steven-a-wilson** [comment]
As far as I've read about it, this problem is specific to one particular 4am release, with there being both a fixed 4am version of The Oregon Trail v1.1 as well as a 4am release of The Oregon Trail v1.4 (I don't know what the differences are between v1.1 and v1.4). Anyway, that's probably a discussion more suited to the MiSTer forums than GitHub.
